config/routes.rb
Rails.application.routes.draw do
  resources :repair_order_details
  resources :repair_orders
  root 'repair_orders#index'

end

app/models/repair_detail.rb
class RepairDetail < ActiveRecord::Base
end

app/controllers/repair_details_controller.rb
class RepairDetailsController < ApplicationController
  before_action :set_repair_detail, only: [:show, :edit, :update, :destroy]

  # GET /repair_details
  # GET /repair_details.json
  def index
    @repair_details = RepairDetail.all
  end

  # GET /repair_details/1
  # GET /repair_details/1.json
  def show
  end

  # GET /repair_details/new
  def new
    @repair_detail = RepairDetail.new
  end

  # GET /repair_details/1/edit
  def edit
  end

  # POST /repair_details
  # POST /repair_details.json
  def create
    @repair_detail = RepairDetail.new(repair_detail_params)

    respond_to do |format|
      if @repair_detail.save
        format.html { redirect_to @repair_detail, notice: 'Repair detail was successfully created.' }
        format.json { render :show, status: :created, location: @repair_detail }
      else
        format.html { render :new }
        format.json { render json: @repair_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /repair_details/1
  # PATCH/PUT /repair_details/1.json
  def update
    respond_to do |format|
      if @repair_detail.update(repair_detail_params)
        format.html { redirect_to @repair_detail, notice: 'Repair detail was successfully updated.' }
        format.json { render :show, status: :ok, location: @repair_detail }
      else
        format.html { render :edit }
        format.json { render json: @repair_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /repair_details/1
  # DELETE /repair_details/1.json
  def destroy
    @repair_detail.destroy
    respond_to do |format|
      format.html { redirect_to repair_details_url, notice: 'Repair detail was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_repair_detail
      @repair_detail = RepairDetail.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def repair_detail_params
      params.require(:repair_detail).permit(:repair_order, :recommendations, :maintenance)
    end
end

app/helpers/repair_details_helper.rb
module RepairDetailsHelper
end

app/views/repair_details/_form.html.erb
<%= form_for(@repair_detail) do |f| %>
  <% if @repair_detail.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@repair_detail.errors.count, "error") %> prohibited this repair_detail from being saved:</h2>

      <ul>
      <% @repair_detail.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :repair_order %><br>
    <%= f.number_field :repair_order %>
  </div>
  <div class="field">
    <%= f.label :recommendations %><br>
    <%= f.text_area :recommendations %>
  </div>
  <div class="field">
    <%= f.label :maintenance %><br>
    <%= f.text_area :maintenance %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/repair_details/edit.html.erb
<h1>Editing Repair Detail</h1>

<%= render 'form' %>

<%= link_to 'Show', @repair_detail %> |
<%= link_to 'Back', repair_details_path %>

app/views/repair_details/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Repair Details</h1>

<table>
  <thead>
    <tr>
      <th>Repair order</th>
      <th>Recommendations</th>
      <th>Maintenance</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @repair_details.each do |repair_detail| %>
      <tr>
        <td><%= repair_detail.repair_order %></td>
        <td><%= repair_detail.recommendations %></td>
        <td><%= repair_detail.maintenance %></td>
        <td><%= link_to 'Show', repair_detail %></td>
        <td><%= link_to 'Edit', edit_repair_detail_path(repair_detail) %></td>
        <td><%= link_to 'Destroy', repair_detail, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Repair detail', new_repair_detail_path %>

app/views/repair_details/new.html.erb
<h1>New Repair Detail</h1>

<%= render 'form' %>

<%= link_to 'Back', repair_details_path %>

app/views/repair_details/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Repair order:</strong>
  <%= @repair_detail.repair_order %>
</p>

<p>
  <strong>Recommendations:</strong>
  <%= @repair_detail.recommendations %>
</p>

<p>
  <strong>Maintenance:</strong>
  <%= @repair_detail.maintenance %>
</p>

<%= link_to 'Edit', edit_repair_detail_path(@repair_detail) %> |
<%= link_to 'Back', repair_details_path %>