config/routes.rb
Rails.application.routes.draw do
  resources :repair_order_details
  resources :repair_orders
  root 'repair_orders#index'

end

app/models/repair_order_detail.rb
class RepairOrderDetail < ActiveRecord::Base
  belongs_to :repair_order
end

app/controllers/repair_order_details_controller.rb
class RepairOrderDetailsController < ApplicationController
  before_action :set_repair_order_detail, only: [:show, :edit, :update, :destroy]

  # GET /repair_order_details
  # GET /repair_order_details.json
  def index
    @repair_order_details = RepairOrderDetail.all
  end

  # GET /repair_order_details/1
  # GET /repair_order_details/1.json
  def show
  end

  # GET /repair_order_details/new
  def new
    @repair_order_detail = RepairOrderDetail.new
  end

  # GET /repair_order_details/1/edit
  def edit
  end

  # POST /repair_order_details
  # POST /repair_order_details.json
  def create
    @repair_order_detail = RepairOrderDetail.new(repair_order_detail_params)

    respond_to do |format|
      if @repair_order_detail.save
        format.html { redirect_to @repair_order_detail, notice: 'Repair order detail was successfully created.' }
        format.json { render :show, status: :created, location: @repair_order_detail }
      else
        format.html { render :new }
        format.json { render json: @repair_order_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /repair_order_details/1
  # PATCH/PUT /repair_order_details/1.json
  def update
    respond_to do |format|
      if @repair_order_detail.update(repair_order_detail_params)
        format.html { redirect_to @repair_order_detail, notice: 'Repair order detail was successfully updated.' }
        format.json { render :show, status: :ok, location: @repair_order_detail }
      else
        format.html { render :edit }
        format.json { render json: @repair_order_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /repair_order_details/1
  # DELETE /repair_order_details/1.json
  def destroy
    @repair_order_detail.destroy
    respond_to do |format|
      format.html { redirect_to repair_order_details_url, notice: 'Repair order detail was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_repair_order_detail
      @repair_order_detail = RepairOrderDetail.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def repair_order_detail_params
      params.require(:repair_order_detail).permit(:cause, :correction, :parts)
    end
end

app/helpers/repair_order_details_helper.rb
module RepairOrderDetailsHelper
end

app/views/repair_order_details/_form.html.erb
<%= form_for(@repair_order_detail) do |f| %>
  <% if @repair_order_detail.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@repair_order_detail.errors.count, "error") %> prohibited this repair_order_detail from being saved:</h2>

      <ul>
      <% @repair_order_detail.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :cause %><br>
    <%= f.text_area :cause %>
  </div>
  <div class="field">
    <%= f.label :correction %><br>
    <%= f.text_area :correction %>
  </div>
  <div class="field">
    <%= f.label :parts %><br>
    <%= f.text_area :parts %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/repair_order_details/edit.html.erb
<h1>Editing Repair Order Detail</h1>

<%= render 'form' %>

<%= link_to 'Show', @repair_order_detail %> |
<%= link_to 'Back', repair_order_details_path %>

app/views/repair_order_details/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Repair Order Details</h1>

<table>
  <thead>
    <tr>
      <th>Cause</th>
      <th>Correction</th>
      <th>Parts</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @repair_order_details.each do |repair_order_detail| %>
      <tr>
        <td><%= repair_order_detail.cause %></td>
        <td><%= repair_order_detail.correction %></td>
        <td><%= repair_order_detail.parts %></td>
        <td><%= link_to 'Show', repair_order_detail %></td>
        <td><%= link_to 'Edit', edit_repair_order_detail_path(repair_order_detail) %></td>
        <td><%= link_to 'Destroy', repair_order_detail, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Repair order detail', new_repair_order_detail_path %>

app/views/repair_order_details/new.html.erb
<h1>New Repair Order Detail</h1>

<%= render 'form' %>

<%= link_to 'Back', repair_order_details_path %>

app/views/repair_order_details/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Cause:</strong>
  <%= @repair_order_detail.cause %>
</p>

<p>
  <strong>Correction:</strong>
  <%= @repair_order_detail.correction %>
</p>

<p>
  <strong>Parts:</strong>
  <%= @repair_order_detail.parts %>
</p>

<%= link_to 'Edit', edit_repair_order_detail_path(@repair_order_detail) %> |
<%= link_to 'Back', repair_order_details_path %>