config/routes.rb
Rails.application.routes.draw do
  resources :repair_order_details
  resources :repair_orders
  root 'repair_orders#index'

end

app/models/repair_order.rb
class RepairOrder < ActiveRecord::Base
  validates_uniqueness_of :number
  
  has_many :repair_order_details
end

app/controllers/repair_orders_controller.rb
class RepairOrdersController < ApplicationController
  before_action :set_repair_order, only: [:show, :edit, :update, :destroy]

  # GET /repair_orders
  # GET /repair_orders.json
  def index
    @repair_orders = RepairOrder.all
  end

  # GET /repair_orders/1
  # GET /repair_orders/1.json
  def show
  end

  # GET /repair_orders/new
  def new
    @repair_order = RepairOrder.new
  end

  # GET /repair_orders/1/edit
  def edit
  end

  # POST /repair_orders
  # POST /repair_orders.json
  def create
    @repair_order = RepairOrder.new(repair_order_params)

    respond_to do |format|
      if @repair_order.save
        format.html { redirect_to @repair_order, notice: 'Repair order was successfully created.' }
        format.json { render :show, status: :created, location: @repair_order }
      else
        format.html { render :new }
        format.json { render json: @repair_order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /repair_orders/1
  # PATCH/PUT /repair_orders/1.json
  def update
    respond_to do |format|
      if @repair_order.update(repair_order_params)
        format.html { redirect_to @repair_order, notice: 'Repair order was successfully updated.' }
        format.json { render :show, status: :ok, location: @repair_order }
      else
        format.html { render :edit }
        format.json { render json: @repair_order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /repair_orders/1
  # DELETE /repair_orders/1.json
  def destroy
    @repair_order.destroy
    respond_to do |format|
      format.html { redirect_to repair_orders_url, notice: 'Repair order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_repair_order
      @repair_order = RepairOrder.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def repair_order_params
      params.require(:repair_order).permit(:number, :recommendations, :maintenance)
    end
end

app/helpers/repair_orders_helper.rb
module RepairOrdersHelper
end

app/views/repair_orders/_form.html.erb
<%= form_for(@repair_order) do |f| %>
  <% if @repair_order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@repair_order.errors.count, "error") %> prohibited this repair_order from being saved:</h2>

      <ul>
      <% @repair_order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :number %><br>
    <%= f.number_field :number %>
  </div>
  <div class="field">
    <%= f.label :recommendations %><br>
    <%= f.text_area :recommendations %>
  </div>
  <div class="field">
    <%= f.label :maintenance %><br>
    <%= f.text_area :maintenance %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/repair_orders/edit.html.erb
<h1>Editing Repair Order</h1>

<%= render 'form' %>

<%= link_to 'Show', @repair_order %> |
<%= link_to 'Back', repair_orders_path %>

app/views/repair_orders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Repair Orders</h1>

<table>
  <thead>
    <tr>
      <th>Number</th>
      <th>Recommendations</th>
      <th>Maintenance</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @repair_orders.each do |repair_order| %>
      <tr>
        <td><%= repair_order.number %></td>
        <td><%= repair_order.recommendations %></td>
        <td><%= repair_order.maintenance %></td>
        <td><%= link_to 'Show', repair_order %></td>
        <td><%= link_to 'Edit', edit_repair_order_path(repair_order) %></td>
        <td><%= link_to 'Destroy', repair_order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Repair order', new_repair_order_path %>

app/views/repair_orders/new.html.erb
<h1>New Repair Order</h1>

<%= render 'form' %>

<%= link_to 'Back', repair_orders_path %>

app/views/repair_orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Number:</strong>
  <%= @repair_order.number %>
</p>

<p>
  <strong>Recommendations:</strong>
  <%= @repair_order.recommendations %>
</p>

<p>
  <strong>Maintenance:</strong>
  <%= @repair_order.maintenance %>
</p>

<%= link_to 'Edit', edit_repair_order_path(@repair_order) %> |
<%= link_to 'Back', repair_orders_path %>